name: long_life_burning
description: Application community for workout.
version: 1.0.0+1
author: Long Life Burning <long.life.burning.1@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #uuid: ^2.0.2
  intl: ^0.15.8
  cached_network_image: ^1.1.3
  background_fetch: ^0.3.2
  #scoped_model: ^1.0.1
  #connectivity: ^0.4.5+3
  #url_launcher: ^5.2.5
  #permission_handler: ^4.0.0
  #page_transition: ^1.1.5
  #percent_indicator: ^2.1.1+1
  flutter_sparkline: ^0.1.0
  charts_flutter: ^0.8.1
  syncfusion_flutter_charts: ^17.3.26

  # Stage management
  provider: ^3.1.0+1
  flutter_redux: ^0.5.4
  #path_provider: ^1.4.0
  
  # Firebase
  firebase_auth: ^0.14.0+8
  cloud_firestore: ^0.12.10
  firebase_messaging: ^5.1.8
  #firebase_database: ^3.0.9
  #firebase_storage: ^3.0.8
  #firebase_storage_image: ^0.4.0
  #cloud_functions: ^0.4.1+4

  # Notify
  flutter_local_notifications: ^0.8.4
  #badges: ^1.1.0

  # Share
  #share: ^0.6.3+1
  #esys_flutter_share: ^1.0.2
  #flutter_share_me: ^0.7.0

  # Database
  sqflite: ^1.1.7+2
  shared_preferences: ^0.5.4+3

  # Map
  location: ^2.3.5
  geolocator: ^5.1.5
  google_maps_flutter: ^0.5.21+8
  google_maps_webservice: ^0.0.16
  #geoflutterfire: ^2.0.3+5
  #flutter_google_places: ^0.2.3
  #clustering_google_maps: ^0.1.2
  #flutter_polyline_points: ^0.1.0

  # Pedometer
  pedometer: ^1.0.0
  fit_kit: ^0.0.6
  #flutter_health: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  test: any
  #gherkin: ^1.1.3
  #flutter_gherkin: ^1.1.4
  #mockito: ^4.1.1
  #ozzie: ^2.2.3
  #pedantic: ">=1.5.0 <=1.8.0+1"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    # style italic or normal
    # weight between 100 and 900
    - family: CupertinoIcons
      fonts:
        - asset: assets/fonts/CupertinoIcons.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/raleway/Raleway-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/raleway/Raleway-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Sarabun
      fonts:
        - asset: assets/fonts/sarabun/Sarabun-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/sarabun/Sarabun-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/sarabun/Sarabun-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-BoldItalic.ttf
          weight: 700
          style: italic
